# -*- coding: utf-8 -*-
"""MCM2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp7pZXg0h-lskJf_wGBjO6I-4loTUkiQ

# 数据处理
"""

import numpy as np
import pandas as pd
from scipy.optimize import linprog
df = pd.read_csv("2026_MCM_Problem_C_Data.csv")

# 显示所有列
pd.set_option('display.max_columns', None)

# 显示所有行
pd.set_option('display.max_rows', None)

df.head(10)

df.drop(df[df["results"]=="Withdrew"].index, inplace=True)
df["celebrity_industry"] = df["celebrity_industry"].str.lower()
def extract_elimination_week(result):
    if isinstance(result, str) and "Eliminated Week" in result:
        return int(result.split()[-1])
    else:
        return np.nan  # 没有被淘汰，比如冠军/亚军/季军

df["eliminated_week"] = df["results"].apply(extract_elimination_week)

#已淘汰选手分数从0改为nan
for index, row in df.iterrows():
    elim_week = row["eliminated_week"]
    if pd.isna(elim_week):
        continue  # 未被淘汰的选手不用处理
    for week in range(int(elim_week)+1, 12):  # 从淘汰周开始，包括本周
        for judge in range(1, 5):  # 最多 4 位评委
            col_name = f"week{week}_judge{judge}_score"
            if col_name in df.columns:
                df.loc[index, col_name] = np.nan
df.head()

#宽表变长表，每人每周一条数据
long_data = []

#每周最多到 week11，每周最多有 4 位评委
for week in range(1, 12):
    week_cols = [f"week{week}_judge{i}_score" for i in range(1, 5)]
    existing_cols = [col for col in week_cols if col in df.columns]

    temp = df[["celebrity_name", "ballroom_partner", "celebrity_industry", "celebrity_homestate","celebrity_homecountry/region","celebrity_age_during_season","season", "placement", "eliminated_week"] + existing_cols].copy()
    temp["week"] = week
    temp["total_judge_score"] = temp[existing_cols].sum(axis=1, skipna=True)
    temp["num_judges"] = temp[existing_cols].notna().sum(axis=1)
    temp["average_judge_score"] = temp["total_judge_score"] / temp["num_judges"]

    # 是否在本周被淘汰
    temp["eliminated"] = temp["eliminated_week"] == week
    # 是否仍在比赛中（未被淘汰或淘汰周 > 当前周）
    temp["still_in_competition"] = temp["total_judge_score"] !=0

    long_data.append(temp[["celebrity_name", "ballroom_partner", "celebrity_industry", "celebrity_homestate", "celebrity_homecountry/region","celebrity_age_during_season", "season", "week", "placement", "eliminated_week", "total_judge_score", "average_judge_score", "num_judges", "eliminated", "still_in_competition"]])

#拼接成统一的 DataFrame
weekly = pd.concat(long_data, ignore_index=True)
long_df = weekly.sort_values(by= ["season", "week"], ignore_index=True)

#添加每个week的rank
long_df["score_rank"] = long_df[long_df["still_in_competition"]].groupby(["season", "week"])["total_judge_score"].rank(ascending=False, method="min")

#添加每个week的percentage
weekly_total_score = (
    long_df[long_df["still_in_competition"]]
    .groupby(["season", "week"])["total_judge_score"]
    .sum()
    .reset_index()
    .rename(columns={"total_judge_score": "weekly_total_score"})
)

# Step 2: 合并进 long_df
long_df = long_df.merge(weekly_total_score, on=["season", "week"], how="left")

# Step 3: 计算百分比
long_df["score_percent"] = long_df["total_judge_score"] / long_df["weekly_total_score"]
long_df.head(20)

valid_weeks = (
    long_df
    .groupby(['season', 'week'])["total_judge_score"]
    .sum()
    .reset_index()
)

# 只保留评分总和 > 0 的周
valid_weeks = valid_weeks[valid_weeks["total_judge_score"] > 0]

# 合并回 long_df，只保留这些 valid weeks
long_df = long_df.merge(valid_weeks[['season', 'week']], on=['season', 'week'], how='inner')

long_df = long_df[long_df["still_in_competition"] == True]
long_df = long_df.reset_index(drop=True)
long_df.head(20)

long_df.to_csv("clean_df.csv", index=False)

"""# 第一问

## 线性规划

### 票数百分比
"""

def elimination_stats(df, season):
  stats = (
    df[df["season"] == season]
    .groupby("week")["eliminated"]
    .sum()
    .reset_index(name="num_eliminated")
  )
  print(stats)
elimination_stats(long_df, 3)

#一般情况
def solve_week_lp(df_week):

    df_week = df_week.reset_index(drop=True)
    n = len(df_week)
    elim_idx = df_week[df_week["eliminated"]].index[0]  # 被淘汰者的行索引
    y = df_week["score_percent"].values                 # y_i 是裁判得分百分比

    # linprog setup
    c = np.zeros(n)  # 无目标函数，仅为可行解
    A_eq = [np.ones(n)]
    b_eq = [1]

    A_ub = []
    b_ub = []

    delta = 1e-6
    for j in range(n):
        if j == elim_idx:
            continue
        constraint = np.zeros(n)
        constraint[elim_idx] = 1   # x_elim
        constraint[j] = -1         # -x_j
        rhs = y[j] - y[elim_idx] - delta   # y_j - y_elim

        A_ub.append(constraint)
        b_ub.append(rhs)

    bounds = [(0, None) for _ in range(n)]  # x_i ≥ 0

    res = linprog(c=c, A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

    if not res.success:
        print("线性规划失败！")
        return None

    audience_min = []
    audience_max = []

    for i in range(n):
      # 求最小 x[i]
      c_min = np.zeros(n)
      c_min[i] = 1
      res_min = linprog(c=c_min, A_eq=A_eq, b_eq=b_eq,
                          A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

        # 求最大 x[i]
      c_max = np.zeros(n)
      c_max[i] = -1
      res_max = linprog(c=c_max, A_eq=A_eq, b_eq=b_eq,
                          A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

      if res_min.success and res_max.success:
          audience_min.append(res_min.fun)
          audience_max.append(-res_max.fun)  # 注意取负

      else:
          audience_min.append(None)
          audience_max.append(None)

    # ===== 构造结果 =====
    df_week = df_week.copy()
    df_week["audience_percent"] = res.x
    df_week["audience_min"] = audience_min
    df_week["audience_max"] = audience_max
    df_week["combined_score"] = df_week["score_percent"] + df_week["audience_percent"]
    df_week["combined_min"] = df_week["score_percent"] + df_week["audience_min"]
    df_week["combined_max"] = df_week["score_percent"] + df_week["audience_max"]

    return df_week


results = []

for week, df_week in long_df[(long_df["season"] == 4) & (long_df["still_in_competition"] == True)].groupby("week"):
    if df_week["eliminated"].sum() > 1:
        print(f"Week {week}: 淘汰人数大于1，跳过")
        continue
    elif df_week["eliminated"].sum() < 1:
      print(f"Week {week}: 没有人淘汰，暂时跳过")
      continue
    res = solve_week_lp(df_week)
    if res is not None:
        results.append(res)

seasona1_lp_result = pd.concat(results, ignore_index=True)

seasona1_lp_result

import matplotlib.pyplot as plt

seasona1_lp_result["diff"] = seasona1_lp_result["audience_max"] - seasona1_lp_result["audience_min"]
seasona1_lp_result

plt.scatter(x = seasona1_lp_result["week"], y = seasona1_lp_result["diff"])
plt.show()

#最后一周的情况
def solve_final_week_lp(df_week):
    df_week = df_week.reset_index(drop=True)
    n = len(df_week)
    y = df_week["score_percent"].values

    sorted_indices = df_week.sort_values("placement").index.tolist()

    c_dummy = np.zeros(n)
    A_eq = [np.ones(n)]
    b_eq = [1]
    A_ub = []
    b_ub = []

    # 根据排名构造顺序约束
    delta = 1e-6
    for i in range(n):
        for j in range(i + 1, n):
            i_better = sorted_indices[i]
            i_worse = sorted_indices[j]

            constraint = np.zeros(n)
            constraint[i_worse] = 1   # x_worse
            constraint[i_better] = -1 # -x_better
            rhs = y[i_better] - y[i_worse] - delta # score_better - score_worse

            A_ub.append(constraint)
            b_ub.append(rhs)

    bounds = [(0, None)] * n

    res = linprog(c=c_dummy, A_eq=A_eq, b_eq=b_eq,
                  A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")

    if not res.success:
        print("规划失败")
        return None

    # audience range for each player
    audience_min = []
    audience_max = []

    for i in range(n):
        # min
        c_min = np.zeros(n)
        c_min[i] = 1
        res_min = linprog(c=c_min, A_eq=A_eq, b_eq=b_eq,
                          A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")
        # max
        c_max = np.zeros(n)
        c_max[i] = -1
        res_max = linprog(c=c_max, A_eq=A_eq, b_eq=b_eq,
                          A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")

        if res_min.success and res_max.success:
            audience_min.append(res_min.fun)
            audience_max.append(-res_max.fun)
        else:
            audience_min.append(None)
            audience_max.append(None)

    df_week = df_week.copy()
    df_week["audience_percent"] = res.x
    df_week["audience_min"] = audience_min
    df_week["audience_max"] = audience_max
    df_week["combined_score"] = df_week["score_percent"] + df_week["audience_percent"]
    df_week["combined_min"] = df_week["score_percent"] + df_week["audience_min"]
    df_week["combined_max"] = df_week["score_percent"] + df_week["audience_max"]

    return df_week

results = []

final_week = long_df[(long_df["season"] == 4) & (long_df["week"] == 10) & (long_df["still_in_competition"] == True)]
final_result = solve_final_week_lp(final_week)
final_result[["celebrity_name", "placement", "score_percent","audience_percent", "audience_min", "audience_max", "combined_score"]]

"""### 票数排名"""



"""## 贝叶斯v1"""

import pymc as pm
import arviz as az

def wk1_fanvote_model(r_J, alpha=2.0, beta=1.0, w=0.5):
    N = len(r_J)
    with pm.Model() as model:
      x = pm.Dirichlet("x", a=np.ones(N) * alpha)
      # 危险度 z 可照常构造
      z = w * r_J - (1 - w) * x * N
      p_elim = pm.math.softmax(beta * z)
      # ❌ 不提供 eliminated_idx → 模型只采样 x，没有观测约束

      return model

def bayesian_fanvote_model(r_J, eliminated_idx, alpha=2.0, beta=1.0, w=0.5):
    N = len(r_J)  # 本轮选手数

    with pm.Model() as model:
        # Dirichlet prior over audience shares
        x = pm.Dirichlet("x", a=np.ones(N) * alpha)

        # 构造“危险度”score（连续形式）
        # r_J 越大越危险
        # x 越小越危险 → 用 -x
        z = w * r_J - (1 - w) * x * N   # 乘 N 让量级接近

        # Softmax likelihood
        p_elim = pm.math.softmax(beta * z)

        # Observed elimination
        elim = pm.Categorical("elim", p=p_elim, observed=eliminated_idx)

    return model

def final_fanvote_model(r_J, placement, alpha=2.0, beta=1.0, w=0.5):
  N = len(r_J)  # 本轮选手数

  ranked_indices = placement.argsort()

  with pm.Model() as model:
        x = pm.Dirichlet("x", a=np.ones(N) * alpha)
        z = -x * N  # 投票多者排前面
        p_rank = pm.math.softmax(beta * z)

        # 多个 soft 观察：rank1, rank2, rank3...
        for i, idx in enumerate(ranked_indices):
            pm.Categorical(f"rank_{i+1}", p=p_rank, observed=idx)

  return model

# 存储所有结果
records = []
df_season4 = long_df[long_df["season"]==3]
# 遍历所有周（按 season, week 分组）
for (season, week), df_week in df_season4.groupby(["season", "week"]):
    df_week = df_week[df_week["still_in_competition"]==True].reset_index(drop=True)

    r_J = df_week["score_rank"].values
    contestants = df_week["celebrity_name"].tolist()
    if df_week["eliminated"].sum() > 1:
      continue
    # 第一周的情况
    if df_week["eliminated"].sum() == 0 & week == 1:
      with wk1_fanvote_model(r_J):
        trace = pm.sample(draws=2000, tune=1000, chains=2, target_accept=0.9)
    elif df_week["eliminated"].sum() == 0 & week != 1:
      placement = df_week["placement"]
      with final_fanvote_model(r_J, placement):
        trace = pm.sample(draws=2000, tune=1000, chains=2, target_accept=0.9)
    else:
      eliminated_name = df_week[df_week["eliminated"] == True]["celebrity_name"].values[0]
      eliminated_idx = contestants.index(eliminated_name)

      with bayesian_fanvote_model(r_J, eliminated_idx):
        trace = pm.sample(draws=2000, tune=1000, chains=2, target_accept=0.9)

    # 提取后验均值和 90% credible interval
    x_samples = trace.posterior["x"]
    x_mean = x_samples.mean(dim=["chain", "draw"]).values
    hdi = az.hdi(x_samples, hdi_prob=0.9)["x"]  # shape: (2, N)
    x_lower = hdi.sel(hdi="lower").values
    x_upper = hdi.sel(hdi="higher").values
    # 保存每位选手的记录
    for i, name in enumerate(contestants):
      records.append({
          "season": season,
          "week": week,
          "celebrity": name,
          "x_mean": x_mean[i],
          "x_lower": x_lower[i],
          "x_upper": x_upper[i],
          "eliminated": (i == eliminated_idx)
      })

# 转成DataFrame
result_df = pd.DataFrame(records)

result_df.to_csv("fanvote_results.csv", index=False)

"""## 贝叶斯v2 (人气计算）"""

import matplotlib.pyplot as plt

# 1. 从 long_df 提取每个 celebrity 的所属 season
celebrity_season = long_df.groupby("celebrity_name")["season"].first()
avg_score = long_df.groupby("celebrity_name")["total_judge_score"].mean()
# 1. 获取每季总人数
total_in_season = long_df.groupby("season")["celebrity_name"].nunique()

# 2. 获取每个人的名次
placement = long_df.groupby("celebrity_name")["placement"].first()

# 3. 获取选手所属赛季
celebrity_season = long_df.groupby("celebrity_name")["season"].first()

# 4. 计算 normalized_survival（数值越大表示活得越久）
norm_survival = 1 - (placement - 1) / celebrity_season.map(total_in_season)

#final_rank = long_df.groupby("celebrity_name")["placement"].first()
plt.scatter(x = avg_score, y = norm_survival)
plt.show()

import seaborn as sns
popularity_df = pd.DataFrame()
popularity_df["avg_score"] = avg_score
popularity_df["norm_survival"] = norm_survival
median_score = popularity_df["avg_score"].median()
median_week = popularity_df["norm_survival"].median()

popularity_df["suspected_popular"] = (
    (popularity_df["avg_score"] < median_score) &
    (popularity_df["norm_survival"] > median_week)
)
sns.scatterplot(
    data=popularity_df,
    x="avg_score",
    y="norm_survival",
    hue="suspected_popular",
    palette={True: "red", False: "blue"}
)
plt.title("Possible High-Popularity Contestants")
plt.show()

# 使用whitegrid主题
sns.set_theme(style="whitegrid", context="talk")

plt.figure(figsize=(10, 7))

ax = sns.scatterplot(
    data=popularity_df,
    x="avg_score",
    y="norm_survival",
    hue="suspected_popular",
    s=90,
    alpha=0.8,
    edgecolor="white",
    linewidth=0.6
)

# 中位数参考线
plt.axvline(median_score, linestyle="--", linewidth=1.2)
plt.axhline(median_week, linestyle="--", linewidth=1.2)

plt.title("Contestant Popularity Structure", fontsize=16, weight="bold")
plt.xlabel("Average Judge Score")
plt.ylabel("Normalized Survival Weeks")

# 优化legend标题
ax.legend(title="Suspected Popular")

sns.despine()
plt.tight_layout()
plt.show()

# 回归模型
from sklearn.linear_model import LinearRegression

X = popularity_df[["avg_score"]]
y = popularity_df["norm_survival"]

reg = LinearRegression().fit(X, y)
popularity_df["expected_week"] = reg.predict(X)

# 残差 = 实际生存周数 - 预测生存周数
popularity_df["residual"] = popularity_df["norm_survival"] - popularity_df["expected_week"]

# 残差排序
top_fans = popularity_df.sort_values("residual", ascending=False).head(10)
bottom_fans = popularity_df.sort_values("residual", ascending=True).head(10)

# 画残差分布图
sns.histplot(popularity_df["residual"], bins=30, kde=True)
plt.title("Residuals (Actual Survival - Predicted by Judge Score)")
plt.xlabel("Residual")
plt.ylabel("Number of Contestants")
plt.show()

# 统一whitegrid风格
sns.set_theme(style="whitegrid", context="talk")

plt.figure(figsize=(10, 7))

ax = sns.histplot(
    popularity_df["residual"],
    bins=30,
    kde=True,
    stat="count",
    alpha=0.8
)

# 计算top和bottom均值位置
top_threshold = top_fans["residual"].min()
bottom_threshold = bottom_fans["residual"].max()

# 标注竖线
plt.axvline(top_threshold, linestyle="--", linewidth=1.5, label="Top 10 Fan-Favored")
plt.axvline(bottom_threshold, linestyle="--", linewidth=1.5, label="Bottom 10 Underperformers")

plt.title("Residual Distribution of Survival Weeks", fontsize=16, weight="bold")
plt.xlabel("Residual (Actual - Predicted Survival)")
plt.ylabel("Number of Contestants")

plt.legend()
sns.despine()
plt.tight_layout()
plt.show()

"""## 贝叶斯v2（模型）"""

bayes_df = long_df[["celebrity_name", "season", "week", "eliminated", "still_in_competition", "placement","score_rank", "total_judge_score"]]
bayes_df = bayes_df.merge(
    popularity_df[["residual"]],
    left_on="celebrity_name",
    right_index=True,
    how="left"
)

bayes_df = bayes_df.rename(columns={"residual": "mu_prior"})

player_list = bayes_df["celebrity_name"].unique().tolist()
player_idx = {name: idx for idx, name in enumerate(player_list)}
bayes_df.head(20)

valid_weeks = (
    bayes_df
    .groupby(['season', 'week'])["total_judge_score"]
    .sum()
    .reset_index()
)

# 只保留评分总和 > 0 的周
valid_weeks = valid_weeks[valid_weeks["total_judge_score"] > 0]

# 合并回 long_df，只保留这些 valid weeks
bayes_df = bayes_df.merge(valid_weeks[['season', 'week']], on=['season', 'week'], how='inner')

from collections import defaultdict

# 初始化
r_J_dict = defaultdict(dict)         # 每周评委排名
I_t_dict = defaultdict(dict)        # 每周参与者 index
eliminated_dict = defaultdict(dict)  # 每周淘汰选手
placement_dict = defaultdict(dict)  # 每周选手票数排名

# 按 season & week 分组
for (season,week), df_week in bayes_df.groupby(["season", "week"]):
    df_week = df_week[df_week["still_in_competition"]==True].reset_index(drop=True)

    # 当前轮参与选手的 index（在 player_list 中的 index）
    I_t = [player_idx[name] for name in df_week["celebrity_name"]]

    # 评委分数排名（数值越大越危险）
    r_J = df_week["score_rank"].tolist()

    pl = df_week["placement"].tolist()

    # 淘汰者（有可能为 NaN，需要排除）
    eliminated_rows = df_week[df_week["eliminated"] == True]
    if len(eliminated_rows) == 1:
        eliminated_name = eliminated_rows["celebrity_name"].iloc[0]
        eliminated_idx = player_idx[eliminated_name]
    else:
        eliminated_idx = None  # 这一周没人淘汰或数据缺失


    # 保存到字典中
    r_J_dict[int(season)][int(week)] = r_J
    I_t_dict[int(season)][int(week)] = I_t
    placement_dict[int(season)][int(week)] = pl
    if eliminated_idx is not None:
        eliminated_dict[int(season)][int(week)] = eliminated_idx
    else:
        eliminated_dict[int(season)][int(week)] = None

eliminated_dict[2][2]

def hierarchical_vote_model(r_J_dict, eliminated_dict, I_t_dict, mu_prior, max_week, placement, beta=1.0, w=0.5):
    """
    参数说明：
    - r_J_dict: 每轮选手的评委排名 {t: [r1, r2, ...]}
    - eliminated_dict: 每轮被淘汰选手的 index {t: idx}
    - I_t_dict: 每轮参与选手的索引列表 {t: [i1, i2, ...]}
    - tau_dict: 每轮的温度系数 {t: float}
    """

    unique_players = sorted({i for I in I_t_dict.values() for i in I})
    player_index = {p: idx for idx, p in enumerate(unique_players)}
    N = len(unique_players)

    with pm.Model() as model:

        tau_max = 0.8544
        tau_min = 0.2
        kappa = 4.4/(max_week/6)
        t0 = int(max_week / 2)

        # 1. 每个选手的长期人气值 μ_i

        # 2. 每轮建模
        for t in r_J_dict.keys():
            I_t = I_t_dict[t]
            n_t = len(I_t)
            tau_t = tau_min + (tau_max - tau_min) / (1 + pm.math.exp(kappa * (t - t0)))
            r_J_t = r_J_dict[t]
            elim_idx = eliminated_dict[t]

            # 2.1 本轮观众 latent 偏好值
            u_t = pm.Normal(f"u_t{t}", mu=[mu_prior[player_index[i]]*1.2 for i in I_t],
                            sigma=0.15, shape=n_t)

            # 2.2 softmax 得到 x 投票比例
            x = pm.Deterministic(f"x_t{t}", pm.math.softmax(u_t / tau_t))

            # 2.4 算危险度
            z = w * pm.math.constant(r_J_t) - (1 - w) * x * N

            # 2.5 淘汰概率
            p_elim = pm.math.softmax(beta * z)
            p_elim_det = pm.Deterministic(f"p_elim_{t}", p_elim)  # 让它进入trace

            # 2.6 观测淘汰选手

            if elim_idx == None and t == 1:
              continue
            elif elim_idx == None and t != 1:
              ranked_indices = np.array(placement[t]).argsort()
              for i, idx in enumerate(ranked_indices):
                pm.Categorical(f"rank_{i+1}_week{t}", p=p_elim, observed=idx)
            else:
              elim_obs = I_t.index(elim_idx)
              pm.Categorical(f"elim_obs_t{t}", p=p_elim, observed=elim_obs)


    return model

max_week_dict = (
    long_df.groupby("season")["week"]
    .max()
    .to_dict()
)

# 存储所有结果
records = []
err_list = []

# 遍历所有周（按 season 分组）
for season in range(1,35):
    df_season = bayes_df[bayes_df["season"] == season].reset_index(drop=True)
    mu = df_season["mu_prior"]
    max_week = max_week_dict[season]
    with hierarchical_vote_model(r_J_dict[season], eliminated_dict[season], I_t_dict[season], mu, max_week, placement_dict[season]):
      trace = pm.sample(draws=2000, tune=1000, chains=2, target_accept=0.9)

    pred_elim_player = {}  # {t: player_id}
    pred_elim_prob   = {}  # {t: prob}
    hits = []

    for t in range(1, max_week + 1):
      varname = f"x_t{t}"
      if varname in trace.posterior:
        x_t_samples = trace.posterior[varname]
        x_t_mean = x_t_samples.mean(dim=["chain", "draw"]).values
        hdi = az.hdi(x_t_samples, hdi_prob=0.9)[varname]
        x_lower = hdi.sel(hdi="lower").values
        x_upper = hdi.sel(hdi="higher").values
        #x_flat = x_t_samples.stack(sample=("chain", "draw")).values
        #x_flat = x_flat.T
        contestants = df_season[(df_season["week"] == t) & (df_season["still_in_competition"]==True)]["celebrity_name"].tolist()

        p = trace.posterior[f"p_elim_{t}"].mean(("chain","draw")).values  # shape (n_t,)
        j = int(np.argmax(p))             # 这是 I_t 内部的位置索引

        elim_id = eliminated_dict[season][t]
        if elim_id is None:
          continue  # 没有真实淘汰就跳过

        I_t = I_t_dict[season][t]
        pred_id = I_t[j]                          # 预测淘汰者的“选手id”（同一坐标系）
        elim_id = eliminated_dict[season][t]      # 真实淘汰者的“选手id”
        if elim_id is not None:
          elim_obs_pos = I_t.index(elim_id)
        pred_elim_player[t] = pred_id
        pred_elim_prob[t]   = float(p[j])

        print(f"\nSeason {season} Week {t}")
        print(f"I_t list: {I_t}")
        print(f"True eliminated:  name={elim_id}, index_in_I_t={elim_obs_pos}")
        print(f"Pred eliminated:  name={pred_id}, index_in_I_t={j}")
        print(f"Pred probability: {p[j]:.4f}")
        p_draw = trace.posterior[f"p_elim_{t}"].values
        # p_draw shape: (chain, draw, n_t)
        pred_pos = np.argmax(p_draw, axis=-1)                   # (chain, draw)
        pred_id_draw = np.take(np.array(I_t), pred_pos)         # (chain, draw) 直接映射到选手id
        hit = (pred_id_draw == elim_id).mean()        # 这周的posterior命中率
        hits.append(hit)

        df_week =  df_season[df_season["week"] == t+1].reset_index(drop=True)


        # 保存每位选手的记录
        for i, name in enumerate(contestants):
            records.append({
                "season": season,
                "week": t,
                "celebrity": name,
                "x_mean": x_t_mean[i],
                "x_lower": x_lower[i],
                "x_upper": x_upper[i],
            })

    err_list.append(float(np.mean(hits)) if hits else np.nan)


# 转成DataFrame
result_df = pd.DataFrame(records)

err_list

err = pd.DataFrame(err_list, columns=["err"])
err.dropna()

result_df

result_df.to_csv("model2_result.csv")

az.summary(trace)

az.plot_posterior(trace, var_names=["u_t1"])

"""## measure of consistency"""

err_list

result = pd.read_csv("model2_result.csv")
result["ci_width"] = result["x_upper"] - result["x_lower"]

"""## measure of certainty"""

hetero = (
    result.groupby(["season", "week"])["ci_width"]
         .agg(lambda x: x.max() - x.min())
         .reset_index()
         .rename(columns={"ci_width":"heterogeneity"})
)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

for s in hetero["season"].unique():
    temp = hetero[hetero["season"] == s]
    plt.plot(temp["week"], temp["heterogeneity"], alpha=0.4)

plt.xlabel("Week")
plt.ylabel("Heterogeneity (HDI Range)")
plt.title("Uncertainty Heterogeneity Across Seasons")
plt.show()

mean_hetero = (
    hetero.groupby("week")["heterogeneity"]
           .mean()
           .reset_index()
)

std_hetero = (
    hetero.groupby("week")["heterogeneity"]
           .std()
           .reset_index()
)

plt.figure(figsize=(8,5))

plt.plot(mean_hetero["week"], mean_hetero["heterogeneity"], label="Mean")

plt.fill_between(
    mean_hetero["week"],
    mean_hetero["heterogeneity"] - std_hetero["heterogeneity"],
    mean_hetero["heterogeneity"] + std_hetero["heterogeneity"],
    alpha=0.2
)

plt.xlabel("Week")
plt.ylabel("Heterogeneity")
plt.title("Average Uncertainty Heterogeneity Across Seasons")
plt.legend()
plt.savefig("Average Uncertainty Heterogeneity Across Seasons.png", dpi=300, bbox_inches="tight")
plt.show()

"""# 第二问"""

result2 = pd.read_csv("model2_result (1).csv")
long_df["fan_share"] = result2["x_mean"]
long_df.tail()

def apply_rank_method(group):
    group = group.copy()
    group["judge_rank"] = group["total_judge_score"].rank(ascending=False, method="min")
    group["fan_rank"] = group["fan_share"].rank(ascending=False, method="min")
    group["combined_rank_score"] = group["judge_rank"] + group["fan_rank"]
    group["rank_order"] = group["combined_rank_score"].rank(ascending=True, method="min")
    return group

def apply_percent_method(group):
    group = group.copy()
    group["judge_percent"] = group["total_judge_score"] / group["total_judge_score"].sum()
    group["fan_percent"] = group["fan_share"]
    group["combined_percent_score"] = group["judge_percent"] + group["fan_percent"]
    group["percent_order"] = group["combined_percent_score"].rank(ascending=False, method="min")
    return group

df_rank = long_df.groupby(["season","week"]).apply(apply_rank_method).reset_index(drop=True)
df_percent = long_df.groupby(["season","week"]).apply(apply_percent_method).reset_index(drop=True)

compare = df_rank.merge(
    df_percent[["season","week","celebrity_name","combined_percent_score","percent_order"]],
    on=["season","week","celebrity_name"]
)
compare.tail(10)

compare["rank_elim"] = compare["rank_order"] == compare.groupby(["season","week"])["rank_order"].transform("max")
compare["percent_elim"] = compare["percent_order"] == compare.groupby(["season","week"])["percent_order"].transform("max")
compare["rank_last_2"] = compare["rank_order"] == compare.groupby(["season","week"])["rank_order"].transform("max") - 1
compare["percent_last_2"] = compare["percent_order"] == compare.groupby(["season","week"])["percent_order"].transform("max")-1
compare["elim_diff"] = compare["rank_elim"] != compare["percent_elim"]

controversy = ["Jerry Rice", "Billy Ray Cyrus", "Bristol Palin", "Bobby Bones"]
compare_con = compare[compare["celebrity_name"].isin(controversy)]
compare_con

compare_con.to_csv("controversy.csv", index = False)

from scipy.stats import spearmanr

weekly_stats = []

for (s,w), group in compare.groupby(["season","week"]):
    rho, _ = spearmanr(group["rank_order"], group["percent_order"])

    weekly_stats.append({
        "season": s,
        "week": w,
        "rank_percent_spearman": rho
    })

weekly_stats = pd.DataFrame(weekly_stats)
weekly_stats.head()

weekly_diff = compare.groupby(["season","week"])["elim_diff"].any().reset_index()

compare.to_csv("compare.csv", index=False)

fan_influence = []

for (s,w), group in compare.groupby(["season","week"]):

    rho_rank, _ = spearmanr(group["rank_order"], group["fan_rank"])
    rho_percent, _ = spearmanr(group["percent_order"], group["fan_rank"])

    fan_influence.append({
        "season": s,
        "week": w,
        "fan_influence_rank": rho_rank,
        "fan_influence_percent": rho_percent
    })

fan_influence = pd.DataFrame(fan_influence)
fan_influence

import statsmodels.api as sm
reg_df = compare.copy()

from sklearn.preprocessing import StandardScaler

features = ["judge_rank", "fan_rank"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(reg_df[features])
X_scaled = sm.add_constant(X_scaled)

y_scaled = StandardScaler().fit_transform(reg_df[["rank_order"]])
model = sm.OLS(y_scaled, X_scaled).fit()
print(model.summary())

features = ["judge_rank", "fan_rank"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(reg_df[features])

X_scaled = sm.add_constant(X_scaled)

y_scaled = StandardScaler().fit_transform(reg_df[["percent_order"]])
model_percent = sm.OLS(y_scaled, X_scaled).fit()
print(model_percent.summary())

features = ["score_percent", "fan_share"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(reg_df[features])

X_scaled = sm.add_constant(X_scaled)

y_scaled = StandardScaler().fit_transform(reg_df[["percent_order"]])
model_percent = sm.OLS(y_scaled, X_scaled).fit()
print(model_percent.summary())

features = ["score_percent", "fan_share"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(reg_df[features])

X_scaled = sm.add_constant(X_scaled)

y_scaled = StandardScaler().fit_transform(reg_df[["rank_order"]])
model_percent = sm.OLS(y_scaled, X_scaled).fit()
print(model_percent.summary())

"""# 第三问"""

celebrity_df = long_df.groupby("celebrity_name").agg({
    "celebrity_age_during_season": "first",
    "celebrity_industry": "first",
    "total_judge_score": "mean",
    "fan_share": "mean"
}).reset_index()
celebrity_df.head()

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
industry_encoded = encoder.fit_transform(celebrity_df[["celebrity_industry"]])

industry_df = pd.DataFrame(
    industry_encoded,
    columns=encoder.get_feature_names_out(["celebrity_industry"])
)

celebrity_features = pd.concat([
    celebrity_df[["celebrity_age_during_season", "total_judge_score", "fan_share"]],
    industry_df
], axis=1)
celebrity_features.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(celebrity_features)

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

inertia = []
for k in range(1, 8):
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(X_scaled)
    inertia.append(km.inertia_)

plt.plot(range(1, 8), inertia)
plt.xlabel("k")
plt.ylabel("Inertia")
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

celebrity_df["cluster"] = clusters

cluster_summary = celebrity_df.groupby("cluster").agg({
    "total_judge_score": "mean",
    "fan_share": "mean",
    "celebrity_age_during_season": "mean"
})

print(cluster_summary)

# === 1. 计算每个行业平均 fan_share ===
industry_stats = (
    long_df.groupby("celebrity_industry")
      .agg(
          avg_fan_share=("fan_share", "mean"),
          count=("fan_share", "size")
      )
)

# === 2. 过滤样本过少的行业（可调 threshold） ===
threshold = 1
industry_stats = industry_stats[industry_stats["count"] >= threshold]

# === 3. 按平均 fan_share 排序 ===
industry_stats = industry_stats.sort_values("avg_fan_share")

# === 4. 画图 ===
plt.figure(figsize=(10, 8))

plt.barh(
    industry_stats.index,
    industry_stats["avg_fan_share"]
)

plt.xlabel("Average Fan Share")
plt.ylabel("Celebrity Industry")
plt.title("Industry vs Fan Vote Share")

plt.tight_layout()
plt.show()

# 1️⃣ 取需要的列并去掉缺失值
data = long_df[["celebrity_age_during_season", "fan_share"]].dropna()

x = data["celebrity_age_during_season"].values
y = data["fan_share"].values

# 2️⃣ 画散点
plt.figure(figsize=(8,6))
plt.scatter(x, y, alpha=0.6)

# 3️⃣ 加线性趋势线
coef = np.polyfit(x, y, 1)
trend = np.poly1d(coef)

# 为了画线更平滑，排序一下 x
x_sorted = np.sort(x)
plt.plot(x_sorted, trend(x_sorted))

plt.xlabel("Age During Season")
plt.ylabel("Fan Share")
plt.title("Relationship Between Age and Fan Vote Share")

plt.tight_layout()
plt.show()

partner_df = df.groupby("ballroom_partner").agg({
    "judge_total": "mean",
    "fan_share": "mean",
    "week": "count"   # 如果每周一行
}).reset_index()

partner_df.rename(columns={"week": "weeks_survived"}, inplace=True)

X_partner = partner_df[["judge_total", "fan_share", "weeks_survived"]]

scaler = StandardScaler()
X_partner_scaled = scaler.fit_transform(X_partner)

kmeans_partner = KMeans(n_clusters=3, random_state=42)
partner_clusters = kmeans_partner.fit_predict(X_partner_scaled)

partner_df["cluster"] = partner_clusters

print(partner_df.groupby("cluster").mean())

import statsmodels.formula.api as smf

model_j = smf.ols("total_judge_score ~ celebrity_age_during_season + C(celebrity_industry) + C(ballroom_partner) + C(week)", data=long_df)
result_j = model_j.fit()
print(result_j.summary())

sns.set(style="whitegrid", font_scale=1.1)
top_pros = long_df['ballroom_partner'].value_counts().nlargest(10).index
df_top = long_df[long_df['ballroom_partner'].isin(top_pros)]
plt.figure(figsize=(14, 6))
sns.boxplot(
    x='ballroom_partner',
    y='total_judge_score',
    data=df_top,
    palette='Set3'
)

plt.title('Fan Vote Distribution by Pro Partner', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.xlabel('Pro Partner')
plt.ylabel('Fan Vote')
plt.tight_layout()
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
long_df["fan_share_scaled"] = scaler.fit_transform(long_df[["fan_share"]])

import statsmodels.formula.api as smf

# Mixed effects model: fixed effects + random intercept by season
model = smf.mixedlm(
    "average_judge_score ~ celebrity_age_during_season + C(celebrity_industry)",        # 固定效应
    data=long_df,
    groups=long_df["season"],                        # 第一层随机效应：season
    re_formula="1",                             # 默认随机截距
    vc_formula={"pro": "0 + C(ballroom_partner)"} # 第二层随机效应：pro dancer
)
result = model.fit()
print(result.summary())
with open("judge_score_model_summary.txt", "w") as f:
    f.write(result.summary().as_text())

model = smf.mixedlm(
    "fan_share_scaled ~ celebrity_age_during_season + C(celebrity_industry)",        # 固定效应
    data=long_df,
    groups=long_df["season"],                        # 第一层随机效应：season
    re_formula="1",                             # 默认随机截距
    vc_formula={"pro": "0 + C(ballroom_partner)"} # 第二层随机效应：pro dancer
)
result = model.fit()
print(result.summary())
with open("fan_vote_model_summary.txt", "w") as f:
    f.write(result.summary().as_text())

# Recreate the dataframe
data = {
    'Industry': [
        "athlete", "comedian", "con artist", "model",
        "radio personality", "tv personality",
        "social media personality", "age"
    ],
    'Judge_Coef': [-0.367, -0.697, -2.269, -1.017, -1.210, -0.605, 0.063, -0.049],
    'Judge_pval': [0.011, 0.034, 0.054, 0.000, 0.028, 0.000, 0.856, 0.000],
    'Fan_Coef': [0.174, 0.137, -0.659, -0.410, 0.469, -0.005, -0.477, -0.013],
    'Fan_pval': [0.092, 0.562, 0.426, 0.043, 0.232, 0.963, 0.066, 0.000]
}
df = pd.DataFrame(data)

# Add significance
def sig_label(p):
    if p < 0.001: return '***'
    elif p < 0.01: return '**'
    elif p < 0.05: return '*'
    elif p < 0.1: return '†'
    return ''

df['Judge_sig'] = df['Judge_pval'].apply(sig_label)
df['Fan_sig'] = df['Fan_pval'].apply(sig_label)

# Bar plot comparison
fig, ax = plt.subplots(figsize=(12, 6))
x = np.arange(len(df))
width = 0.35

bars1 = ax.bar(x - width/2, df['Judge_Coef'], width, label='Judge Score', color='cornflowerblue')
bars2 = ax.bar(x + width/2, df['Fan_Coef'], width, label='Fan Vote (scaled)', color='lightcoral')

for i, (bar, sig) in enumerate(zip(bars1, df['Judge_sig'])):
    if sig:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height(), sig, ha='center', va='bottom', fontsize=10)

for i, (bar, sig) in enumerate(zip(bars2, df['Fan_sig'])):
    if sig:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height(), sig, ha='center', va='bottom', fontsize=10)

ax.axhline(0, color='gray', linestyle='--')
ax.set_xticks(x)
ax.set_xticklabels(df['Industry'], rotation=45, ha='right')
ax.set_ylabel('Coefficient Estimate')
ax.set_title('Effect of Celebrity Industry on Judge Scores and Fan Votes (with p-value significance)')
ax.legend()
plt.tight_layout()

# Heatmap
heat_df = df.set_index('Industry')[['Judge_Coef', 'Fan_Coef']]
pvals = df.set_index('Industry')[['Judge_pval', 'Fan_pval']]

fig2, ax2 = plt.subplots(figsize=(8, 6))
sns.heatmap(heat_df, annot=True, fmt=".2f", cmap='coolwarm', center=0, cbar_kws={'label': 'Coefficient'}, ax=ax2)

# Add significance marks
for y in range(heat_df.shape[0]):
    for x in range(heat_df.shape[1]):
        sig = sig_label(pvals.iloc[y, x])
        if sig:
            ax2.text(x + 0.5, y + 0.5, sig, ha='center', va='center', color='black', fontsize=11, weight='bold')

ax2.set_title('Coefficient Heatmap of Industry Effects on Judge and Fan Vote\n(† p<0.1, * p<0.05, ** p<0.01, *** p<0.001)')
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import shap

# ====== 1. 特征选择 ======
features = ["celebrity_age_during_season", "celebrity_industry", "ballroom_partner", "week"]
target = "average_judge_score"

X = long_df[features].copy()
y = long_df[target]

# ====== 2. 预处理（one-hot编码类别变量） ======
categorical = ["celebrity_industry", "ballroom_partner"]
numeric = ["celebrity_age_during_season", "week"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("num", "passthrough", numeric)
    ]
)

# ====== 3. 建模管道 ======
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(n_estimators=100, max_depth = 10,random_state=42))
])

# ====== 4. 训练模型 ======
model.fit(X, y)

# ====== 5. 提取预处理后的特征矩阵 ======
X_preprocessed = model.named_steps["preprocessor"].transform(X)
feature_names = model.named_steps["preprocessor"].get_feature_names_out()

# 转换为 DataFrame
X_df = pd.DataFrame(X_preprocessed.toarray() if hasattr(X_preprocessed, 'toarray') else X_preprocessed,
                    columns=feature_names)

# ====== 6. SHAP 解释器 ======
explainer = shap.Explainer(model.named_steps["regressor"], X_df)
shap_values = explainer(X_df)

# ====== 7. 画图：特征贡献条形图 ======
shap.plots.bar(shap_values, max_display=15)

# （可选）更详细的 bee swarm 图
shap.summary_plot(shap_values, X_df, max_display=20)

# ====== 1. 特征选择 ======
features = ["celebrity_age_during_season", "celebrity_industry", "ballroom_partner", "week"]
target = "fan_share_scaled"

X = long_df[features].copy()
y = long_df[target]

# ====== 2. 预处理（one-hot编码类别变量） ======
categorical = ["celebrity_industry", "ballroom_partner"]
numeric = ["celebrity_age_during_season", "week"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("num", "passthrough", numeric)
    ]
)

# ====== 3. 建模管道 ======
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(n_estimators=100, random_state=42))
])

# ====== 4. 训练模型 ======
model.fit(X, y)

# ====== 5. 提取预处理后的特征矩阵 ======
X_preprocessed = model.named_steps["preprocessor"].transform(X)
feature_names = model.named_steps["preprocessor"].get_feature_names_out()

# 转换为 DataFrame
X_df = pd.DataFrame(X_preprocessed.toarray() if hasattr(X_preprocessed, 'toarray') else X_preprocessed,
                    columns=feature_names)

# ====== 6. SHAP 解释器 ======
explainer = shap.Explainer(model.named_steps["regressor"], X_df)
shap_values = explainer(X_df)

# ====== 7. 画图：特征贡献条形图 ======
shap.plots.bar(shap_values, max_display=15)

# （可选）更详细的 bee swarm 图
shap.summary_plot(shap_values, X_df, max_display=20)

!pip install category_encoders

from category_encoders import TargetEncoder
# ====== 1. 特征选择 ======
features = ["celebrity_age_during_season", "celebrity_industry", "ballroom_partner", "week"]
target = "average_judge_score"

X = long_df[features].copy()
y = long_df[target]

# ====== 2. Target Encoding 设置 ======
categorical = ["celebrity_industry", "ballroom_partner"]
numeric = ["celebrity_age_during_season", "week"]

# 使用 category_encoders 的 TargetEncoder
class SklearnCompatibleTargetEncoder(TargetEncoder):
    def fit(self, X, y):
        return super().fit(X, y)

    def transform(self, X):
        return super().transform(X)

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", TargetEncoder(cols=categorical), categorical),
        ("num", "passthrough", numeric)
    ]
)

# ====== 3. 建模管道 ======
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42))
])

# ====== 4. 切分数据集（可选）
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ====== 5. 训练模型 ======
model.fit(X_train, y_train)

# ====== 6. 提取预处理后的特征矩阵 ======
X_preprocessed = model.named_steps["preprocessor"].transform(X_train)
# 获取列名（TargetEncoder 没有 feature_names_out，需要手动加）
feature_names = categorical + numeric
X_df = pd.DataFrame(X_preprocessed, columns=feature_names)

# ====== 7. SHAP 解释器 ======
explainer = shap.Explainer(model.named_steps["regressor"], X_df)
shap_values = explainer(X_df)

# ====== 8. 画图：特征贡献条形图 ======
shap.plots.bar(shap_values, max_display=15)
shap.summary_plot(shap_values, X_df, max_display=20)

"""# 第四问"""

weekly_variances = long_df.groupby(["season", "week"])["fan_share"].var()
weekly_variances_df = weekly_variances.reset_index(name="week_var")
max_variance_per_season = weekly_variances_df.groupby('season')['week_var'].transform('max')
weekly_variances_df["w_fan_raw"] = 1 - (weekly_variances_df["week_var"] / max_variance_per_season)

w_max = 0.7
w_min = 0.3
weekly_variances_df["w_fan_t"] = (w_max - w_min) * weekly_variances_df["w_fan_raw"] + w_min

def normalize_rank(rank_series):
    N = rank_series.count()
    return (N - rank_series + 1) / (N - 1)  # higher = better

long_df["judge_rank"] = long_df.groupby(["season", "week"])["average_judge_score"].rank(ascending=False)
long_df["J_norm"] = long_df.groupby(["season", "week"])["judge_rank"].transform(normalize_rank)

df_temp = long_df.copy()
df_temp = df_temp.merge(weekly_variances_df[["season","week","w_fan_t"]], on=["season", "week"], how="left")
df_temp = df_temp.drop(columns = ["ballroom_partner", "celebrity_industry", "celebrity_homestate", "celebrity_homecountry/region","celebrity_age_during_season"])

df_temp["system_score"] = df_temp["w_fan_t"] * df_temp["fan_share"] + (1 - df_temp["w_fan_t"]) * df_temp["score_percent"]
df_temp.head(50)

from scipy.stats import spearmanr

f1_s1_records = []
W = 3  # 感知公平性的时间窗口
e1_results = []
eta = 1e-6  # 防止除零
e2_results = []

for season in df_temp["season"].unique():
    season_df = df_temp[df_temp["season"] == season]
    all_weeks = sorted(season_df["week"].unique())

    for week in all_weeks:
        df_week = season_df[season_df["week"] == week].copy()

        # 排名
        df_week["system_rank"] = df_week["system_score"].rank(ascending=False)
        df_week["judge_rank"] = df_week["total_judge_score"].rank(ascending=False)

        # F1
        f1, _ = spearmanr(df_week["system_rank"], df_week["judge_rank"])

        # S1
        if week >= W:
            recent_weeks = list(range(week - W + 1, week + 1))
            df_recent = season_df[season_df["week"].isin(recent_weeks)]
            judge_avg = df_recent.groupby("celebrity_name")["total_judge_score"].mean().reset_index(name="recent_judge_score")
            df_week = df_week.merge(judge_avg, on="celebrity_name", how="left")
            df_week["recent_rank"] = df_week["recent_judge_score"].rank(ascending=False)
            s1, _ = spearmanr(df_week["system_rank"], df_week["recent_rank"])
        else:
            s1 = None  # 前几周没有足够窗口
        # 根据 judge 和 system 选出各自的排名最低者（最可能淘汰）
        judge_elim = df_week.loc[df_week['judge_rank'].idxmax()]['celebrity_name']
        system_elim = df_week.loc[df_week['system_rank'].idxmax()]['celebrity_name']
        changed = int(judge_elim != system_elim)
        e1_results.append({'season': season, 'week': week, 'elimination_change': changed})

        if week < df_week['week'].max() - 2:  # late stage = 最后3周
          continue

        # 按SystemScore降序排序，取倒数第二和最后一名的差距
        sorted_scores = df_week.sort_values('system_score', ascending=False)
        margin = sorted_scores.iloc[-2]['system_score'] - sorted_scores.iloc[-1]['system_score']
        e2_results.append({'season': season, 'week': week, 'margin': margin})

        f1_s1_records.append({
            "season": season,
            "week": week,
            "F1": f1,
            "S1": s1
        })

fairness_df = pd.DataFrame(f1_s1_records)
e1_df = pd.DataFrame(e1_results)

# 每季 E1 指标 = 所有change / 总轮数
e1_summary = e1_df.groupby('season')['elimination_change'].agg(['sum', 'count']).reset_index()
e1_summary['E1'] = e1_summary['sum'] / e1_summary['count']

e2_df = pd.DataFrame(e2_results)
e2_df['max_margin'] = e2_df.groupby('season')['margin'].transform('max')
e2_df['margin_norm'] = e2_df['margin'] / (e2_df['max_margin'] + eta)

# 每季 E2 = 1 - 平均相对差距
e2_summary = e2_df.groupby('season')['margin_norm'].mean().reset_index()
e2_summary['E2'] = 1 - e2_summary['margin_norm']

e1_summary.head()

e2_summary.head()

fairness_df.head()

sns.lineplot(data=fairness_df[fairness_df["season"] == 1], x="week", y="F1", label="Technical Fairness F1")
sns.lineplot(data=fairness_df[fairness_df["season"] == 1], x="week", y="S1", label="Perceived Fairness S1")
plt.title("Fairness Metrics Over Time (Season 1)")
plt.ylabel("Spearman Correlation")
plt.show()

df_old = long_df.copy()

df_old = df_old.drop(columns = ["ballroom_partner", "celebrity_industry", "celebrity_homestate", "celebrity_homecountry/region","celebrity_age_during_season"])

df_old["system_score"] = 0.5 * df_old["fan_share"] + 0.5 * df_old["score_percent"]
df_old.head()

f1_s1_records_old = []
W = 3  # 感知公平性的时间窗口
e1_results_old = []
eta = 1e-6  # 防止除零
e2_results_old = []

for season in df_old["season"].unique():
    season_df = df_old[df_old["season"] == season]
    all_weeks = sorted(season_df["week"].unique())

    for week in all_weeks:
        df_week = season_df[season_df["week"] == week].copy()

        # 排名
        df_week["system_rank"] = df_week["system_score"].rank(ascending=False)
        df_week["judge_rank"] = df_week["total_judge_score"].rank(ascending=False)

        # F1
        f1, _ = spearmanr(df_week["system_rank"], df_week["judge_rank"])

        # S1
        if week >= W:
            recent_weeks = list(range(week - W + 1, week + 1))
            df_recent = season_df[season_df["week"].isin(recent_weeks)]
            judge_avg = df_recent.groupby("celebrity_name")["total_judge_score"].mean().reset_index(name="recent_judge_score")
            df_week = df_week.merge(judge_avg, on="celebrity_name", how="left")
            df_week["recent_rank"] = df_week["recent_judge_score"].rank(ascending=False)
            s1, _ = spearmanr(df_week["system_rank"], df_week["recent_rank"])
        else:
            s1 = None  # 前几周没有足够窗口
        # 根据 judge 和 system 选出各自的排名最低者（最可能淘汰）
        judge_elim = df_week.loc[df_week['judge_rank'].idxmax()]['celebrity_name']
        system_elim = df_week.loc[df_week['system_rank'].idxmax()]['celebrity_name']
        changed = int(judge_elim != system_elim)
        e1_results_old.append({'season': season, 'week': week, 'elimination_change': changed})

        if week < df_week['week'].max() - 2:  # late stage = 最后3周
          continue

        # 按SystemScore降序排序，取倒数第二和最后一名的差距
        sorted_scores = df_week.sort_values('system_score', ascending=False)
        margin = sorted_scores.iloc[-2]['system_score'] - sorted_scores.iloc[-1]['system_score']
        e2_results_old.append({'season': season, 'week': week, 'margin': margin})

        f1_s1_records_old.append({
            "season": season,
            "week": week,
            "F1": f1,
            "S1": s1
        })

fairness_df_old = pd.DataFrame(f1_s1_records_old)
e1_df_old = pd.DataFrame(e1_results_old)

# 每季 E1 指标 = 所有change / 总轮数
e1_summary_old = e1_df_old.groupby('season')['elimination_change'].agg(['sum', 'count']).reset_index()
e1_summary_old['E1'] = e1_summary_old['sum'] / e1_summary_old['count']

e2_df_old = pd.DataFrame(e2_results_old)
e2_df_old['max_margin'] = e2_df_old.groupby('season')['margin'].transform('max')
e2_df_old['margin_norm'] = e2_df_old['margin'] / (e2_df_old['max_margin'] + eta)

# 每季 E2 = 1 - 平均相对差距
e2_summary_old = e2_df_old.groupby('season')['margin_norm'].mean().reset_index()
e2_summary_old['E2'] = 1 - e2_summary_old['margin_norm']

fairness_df_old.head()

e1_summary_old.head()

e2_summary_old.head()

df_rank = long_df.copy()

df_rank = df_rank.drop(columns = ["ballroom_partner", "celebrity_industry", "celebrity_homestate", "celebrity_homecountry/region","celebrity_age_during_season"])

df_rank["vote_rank"] = df_rank.groupby(["season", "week"])["fan_share"].rank(ascending=False)
df_rank["system_score"] = 0.5 * df_rank["judge_rank"] + 0.5 * df_rank["vote_rank"]
df_rank.head()

f1_s1_records_rank = []
W = 3  # 感知公平性的时间窗口
e1_results_rank = []
eta = 1e-6  # 防止除零
e2_results_rank = []

for season in df_rank["season"].unique():
    season_df = df_rank[df_rank["season"] == season]
    all_weeks = sorted(season_df["week"].unique())

    for week in all_weeks:
        df_week = season_df[season_df["week"] == week].copy()

        # 排名
        df_week["system_rank"] = df_week["system_score"].rank(ascending=False)
        df_week["judge_rank"] = df_week["total_judge_score"].rank(ascending=False)

        # F1
        f1, _ = spearmanr(df_week["system_rank"], df_week["judge_rank"])

        # S1
        if week >= W:
            recent_weeks = list(range(week - W + 1, week + 1))
            df_recent = season_df[season_df["week"].isin(recent_weeks)]
            judge_avg = df_recent.groupby("celebrity_name")["total_judge_score"].mean().reset_index(name="recent_judge_score")
            df_week = df_week.merge(judge_avg, on="celebrity_name", how="left")
            df_week["recent_rank"] = df_week["recent_judge_score"].rank(ascending=False)
            s1, _ = spearmanr(df_week["system_rank"], df_week["recent_rank"])
        else:
            s1 = None  # 前几周没有足够窗口
        # 根据 judge 和 system 选出各自的排名最低者（最可能淘汰）
        judge_elim = df_week.loc[df_week['judge_rank'].idxmax()]['celebrity_name']
        system_elim = df_week.loc[df_week['system_rank'].idxmax()]['celebrity_name']
        changed = int(judge_elim != system_elim)
        e1_results_rank.append({'season': season, 'week': week, 'elimination_change': changed})

        if week < df_week['week'].max() - 2:  # late stage = 最后3周
          continue

        # 按SystemScore降序排序，取倒数第二和最后一名的差距
        sorted_scores = df_week.sort_values('system_score', ascending=False)
        margin = sorted_scores.iloc[-2]['system_score'] - sorted_scores.iloc[-1]['system_score']
        e2_results_rank.append({'season': season, 'week': week, 'margin': margin})

        f1_s1_records_rank.append({
            "season": season,
            "week": week,
            "F1": f1,
            "S1": s1
        })

fairness_df_rank = pd.DataFrame(f1_s1_records_rank)
e1_df_rank = pd.DataFrame(e1_results_rank)

# 每季 E1 指标 = 所有change / 总轮数
e1_summary_rank = e1_df_rank.groupby('season')['elimination_change'].agg(['sum', 'count']).reset_index()
e1_summary_rank['E1'] = e1_summary_rank['sum'] / e1_summary_rank['count']

e2_df_rank = pd.DataFrame(e2_results_rank)
e2_df_rank['max_margin'] = e2_df_rank.groupby('season')['margin'].transform('max')
e2_df_rank['margin_norm'] = e2_df_rank['margin'] / (e2_df_rank['max_margin'] + eta)

# 每季 E2 = 1 - 平均相对差距
e2_summary_rank = e2_df_rank.groupby('season')['margin_norm'].mean().reset_index()
e2_summary_rank['E2'] = 1 - e2_summary_rank['margin_norm']

print(e1_summary["E1"].mean())
print(e1_summary_old["E1"].mean())
print(e1_summary_rank["E1"].mean())

print(fairness_df["F1"].mean())
print(fairness_df_old["F1"].mean())
print(fairness_df_rank["F1"].mean())
print(fairness_df["S1"].mean())
print(fairness_df_old["S1"].mean())
print(fairness_df_rank["S1"].mean())

print(e2_summary["E2"].mean())
print(e2_summary_old["E2"].mean())
print(e2_summary_rank["E2"].mean())

e2_summary_rank.head()

e1_summary_rank.head()

fairness_df_rank.head()

df_temp.to_csv("system_score.csv", index = False)

plt.figure(figsize=(8,5))

for s in hetero["season"].unique():
    temp = [hetero["season"] == s]
    plt.plot(temp["week"], temp["F1"], alpha=0.4)

plt.xlabel("Week")
plt.ylabel("Heterogeneity (HDI Range)")
plt.title("Uncertainty Heterogeneity Across Seasons")
plt.show()

lst = long_df["celebrity_name"].unique()
len(lst)

"""## 爬数据（Google Trends）"""

pip install pytrends

from pytrends.request import TrendReq
from datetime import datetime, timedelta
import time

# 设置每次请求后的延迟（秒）
REQUEST_DELAY = 60

# 最大重试次数
MAX_RETRIES = 5

# 是否使用代理（可选）
USE_PROXY = False
PROXIES = {
    "http": "http://your_proxy_here",
    "https": "http://your_proxy_here"
}

def fetch_trends(kw_list, timeframe):
    retry_count = 0

    while retry_count < MAX_RETRIES:
        try:
            pytrends = TrendReq(hl='en-US', tz=360, requests_args={"proxies": PROXIES} if USE_PROXY else {})
            pytrends.build_payload(kw_list, cat=0, timeframe=timeframe, geo='', gprop='')
            df = pytrends.interest_over_time()
            if not df.empty:
                df = df.drop(columns=['isPartial'], errors='ignore')
            return df
        except Exception as e:
            print(f"[Retry {retry_count+1}] 网络错误：{e}")
            retry_count += 1
            time.sleep(REQUEST_DELAY * retry_count)  # 指数型回退

    return pd.DataFrame()


# ====== 合并抓取多个名人趋势总分 ======

def get_total_trend_scores(season, start, end):
    names = long_df[long_df["season"] == season]["celebrity_name"]
    timeframe = f"{start} {end}"
    results = []
    for name in names:
        print(f"正在抓取：{name}")
        df = fetch_trends([name], timeframe)
        total_score = df[name].sum() if not df.empty else 0
        results.append({"celebrity_name": name, "total_trend_score": total_score})
        time.sleep(REQUEST_DELAY)  # 固定延迟，避免触发封锁
    return pd.DataFrame(results)


# ====== 执行抓取 ======

if __name__ == "__main__":
    df_s1 = get_total_trend_scores(1, "2005-06-01", "2005-07-06")
    df_s2 = get_total_trend_scores(2, "2006-01-01", "2006-02-24")
    df_s3 = get_total_trend_scores(3, "2006-09-12", "2006-11-15")
    df_s4 = get_total_trend_scores(4, "2007-03-09", "2007-05-22")
    df_s5 = get_total_trend_scores(5, "2007-09-24", "2007-11-27")
    df_s6 = get_total_trend_scores(6, "2008-03-17", "2008-05-20")

    #df_trends.to_csv("trend_scores.csv", index=False)

"""
def get_weekly_trends(keyword, start_date, end_date, geo=''):


    timeframe = f"{start_date} {end_date}"
    pytrends.build_payload([keyword], timeframe=timeframe, geo=geo)
    data = pytrends.interest_over_time()
    if not data.empty:
        return data[[keyword]].rename(columns={keyword: 'trend_score'})
    else:
        print(f"No data for {keyword}")
        return None
"""

def get_all_trends(season, start, end):
  import time
  contestants = long_df[long_df["season"] == season]["celebrity_name"]
  start_date = start
  end_date = end


  all_trends = []

  for name in contestants:
      df = get_weekly_trends(name, start_date, end_date, geo="US")
      if df is not None:
          df["celebrity_name"] = name
          all_trends.append(df.reset_index())

  time.sleep(60)

  # 合并所有选手的时间序列数据
  trends_df = pd.concat(all_trends, ignore_index=True)

  # 创建“周”列（可选：你也可以用 .dt.isocalendar().week 取周号）
  trends_df['week_start'] = trends_df['date'] - trends_df['date'].dt.weekday * pd.Timedelta(days=1)

  # 按选手+每周进行分组并取平均值或最大值
  weekly_trends = (
      trends_df
      .groupby(['celebrity_name', 'week_start'])['trend_score']
      .mean()  # or .max() depending on what you want
      .reset_index()
  )
  weekly_trends["season"] = season
  return weekly_trends

# 查看结果
df_s1 = get_all_trends(1, "2005-06-01", "2005-07-06")
df_s2 = get_all_trends(2, "2006-01-01", "2006-02-24")

df_s3 = get_all_trends(3, "2006-09-12", "2006-11-15")
df_s4 = get_all_trends(4, "2007-03-09", "2007-05-22")

df_s5 = get_all_trends(5, "2007-09-24", "2007-11-27")
df_s6 = get_all_trends(6, "2008-03-17", "2008-05-20")

df_s7 = get_all_trends(7, "2008-09-22", "2008-11-25")
df_s8 = get_all_trends(8, "2009-03-09", "2009-05-19")

df_s9 = get_all_trends(9, "2009-09-21", "2009-11-24")
df_s10 = get_all_trends(10, "2010-03-22", "2010-05-25")

df_s11 = get_all_trends(11, "2010-09-20", "2010-11-23")
df_s12 = get_all_trends(12, "2011-03-21", "2011-05-24")

df_s13 = get_all_trends(13, "2011-09-19", "2011-11-22")
df_s14 = get_all_trends(14, "2012-03-19", "2012-05-22")

df_s15 = get_all_trends(15, "2012-09-24", "2012-11-27")
df_s16 = get_all_trends(16, "2013-03-18", "2013-05-21")

df_s17 = get_all_trends(17, "2013-09-16", "2013-11-26")
df_s18 = get_all_trends(18, "2014-03-17", "2014-05-20")

df_s19 = get_all_trends(19, "2014-09-15", "2014-11-25")
df_s20 = get_all_trends(20, "2015-03-16", "2015-05-19")

df_s21 = get_all_trends(21, "2015-09-14", "2015-11-24")
df_s22 = get_all_trends(22, "2016-03-21", "2016-05-24")

df_s23 = get_all_trends(23, "2016-09-12", "2016-11-22")
df_s24 = get_all_trends(24, "2017-03-20", "2017-05-23")

df_s25 = get_all_trends(25, "2017-09-18", "2017-11-21")
df_s26 = get_all_trends(26, "2018-04-30", "2018-05-21")

df_s27 = get_all_trends(27, "2018-09-24", "2018-11-19")
df_s28 = get_all_trends(28, "2019-09-16", "2019-11-25")

df_s29 = get_all_trends(29, "2020-09-14", "2020-11-23")
df_s30 = get_all_trends(30, "2021-09-20", "2021-11-22")

df_s31 = get_all_trends(31, "2022-09-19", "2022-11-21")
df_s32 = get_all_trends(32, "2023-09-26", "2023-12-05")

df_s33 = get_all_trends(33, "2024-09-17", "2024-11-26")
df_s34 = get_all_trends(34, "2025-09-16", "2025-12-02")

weekly_trends = pd.concat([df_s1, df_s2, df_s3, df_s4, df_s5, df_s6, df_s7, df_s8, df_s9, df_s10,
                           df_s11, df_s12, df_s13, df_s14, df_s15, df_s16, df_s17, df_s18, df_s19, df_s20,
                           df_s21, df_s22, df_s23, df_s24
                           ], ignore_index=True)

# 汇总 trend_score
trend_sum = weekly_trends.groupby("celebrity_name")["trend_score"].sum().reset_index()
trend_sum.rename(columns={"trend_score": "total_trend_score"}, inplace=True)

# 合并最终名次（你已有的选手列表中要有 final_placement 字段）
contestant_info = long_df[["celebrity_name", "placement"]]  # 举例
summary_df = pd.merge(trend_sum, contestant_info, on="celebrity_name").drop_duplicates()
summary_df

import matplotlib.pyplot as plt
import seaborn as sns

# 散点图
sns.scatterplot(data=summary_df, x="total_trend_score", y="placement")
plt.title("Google Trends vs Final Placement")
plt.xlabel("Total Trend Score (sum of weekly scores)")
plt.ylabel("Final Placement (1 = best)")
plt.gca().invert_yaxis()  # 因为 1 名最好，要放在上面
plt.show()

summary_df.iloc[:,1:].corr(method="pearson")